cas:
  client-host-url: http://127.0.0.1:8081
  server-url-prefix: http://localhost:8080/cas
  server-login-url: http://localhost:8080/cas/login
  validation-type: cas3
  use-session: true
  redirect-after-validation: true
server:
  port: 8081
  servlet:
    context-path: /a

spring:
  thymeleaf:
    encoding: utf-8
    cache: true
    mode: HTML
    template-resolver-order: 100

